In [5]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))
print(np.argmin(arr))
print(np.argmax(arr))

150
30.0
30.0
10
50
14.142135623730951
200.0
0
4


In [8]:
#Aggregation on 2d

arr= np.array([[1,2,3],[4,5,6]]
              )

print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

21
[5 7 9]
[ 6 15]


In [20]:
#Boolean Indexing

scores = np.random.randint(1,100,size=(10))
print(scores)
print(scores.shape)
mask = scores >60
print(mask)
print(scores[mask])

[32 64 62  7 73 15 94 35 42 23]
(10,)
[False  True  True False  True False  True False False False]
[64 62 73 94]


In [21]:
mask2 = (scores>70) & (scores<85)
print(mask2)

[False False False False  True False False False False False]


In [ ]:
#Fancy in