In [4]:
import numpy as np

zero=np.zeros((2,9))
print(zero)

one=np.ones((2,9))
print(one)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [5]:
one=np.full((2,9),99)
print(one)

[[99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99]]


In [6]:
arr=np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [16]:
arr=np.linspace(1,10,9)
print(arr)

[ 1.     2.125  3.25   4.375  5.5    6.625  7.75   8.875 10.   ]


In [17]:
arr=np.random.randint(1,100,size=(3,3))
print(arr)

[[80 78 17]
 [23 41 59]
 [25 15 40]]


In [26]:
arr=np.random.random(size=(1,5))
print(arr)

[[0.95987431 0.94995656 0.03825725 0.75031306 0.77608393]]
