In [1]:
import numpy as np

In [6]:
a= np.arange(10,100,20)
b= np.arange(110,200,20)
print(f"A = {a}")
print(f"B = {b}")

A = [10 30 50 70 90]
B = [110 130 150 170 190]


In [7]:
print(a+b)

[120 160 200 240 280]


In [11]:
print(b-a)
print(a*b)
print(a*2)
print(a)

[100 100 100 100 100]
[ 1100  3900  7500 11900 17100]
[ 20  60 100 140 180]
[10 30 50 70 90]


In [12]:
#Masking
print(a>10)

[False  True  True  True  True]


In [13]:
#Broadcasting

print(a + 100)
print(a)

[110 130 150 170 190]
[10 30 50 70 90]


In [15]:
matrix = np.array([[1,2,3],
                  [4,5,6]])

row = np.array([10,20,30])
print(matrix+row)

[[11 22 33]
 [14 25 36]]
