In [3]:
import numpy as np

arr = np.array([10,20,30,40])

print(arr[0])

#slicing
print(arr[1:5:2])

10
[20 40]


In [13]:
arr = np.array([[10,20,30,40],
                [50,60,70,80],
                [1,2,3,4]])


print(arr[0,3])

#full row

print(arr[0])

#full colum
print(arr[:,0])
print(arr[1:3,2:4])

#slicing


40
[10 20 30 40]
[10 50  1]
[[70 80]
 [ 3  4]]
