In [9]:
import numpy as np

arr = np.arange(1,19)

print(f"Array = {arr}")
print(f"Array = {arr.shape}")

Array = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
Array = (18,)


In [17]:
arr=np.zeros((4,3))
print(f"Array = {arr}")
print(f"Array = {arr.shape}")


Array = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array = (4, 3)


In [21]:
reshape = arr.reshape(1,12)
print(f"reshape = {reshape}")

reshape = [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
