In [3]:
import numpy as np
a = np.random.randint(1,100,size=(3))
b = np.random.randint(1,100,size=(3))
print(a)
print(b)
print(np.vstack([a,b]))
print(np.hstack([a,b]))

[13 44 63]
[24 12 61]
[[13 44 63]
 [24 12 61]]
[13 44 63 24 12 61]
